### ISSUE TITLE
didnt refresh bank

### ISSUE THREAD

**Issue by ezrajc** [cs340tabyu/cs340summer2018#14]
There are currently three color cards with two locamotives and I chose one color card. The card i chose was a color card which was replaced along with the other two cards for some reason. but if the replacement card was a wild then all 5 should have been shuffled. Also the bank was updated for me but for no one else, although i have one more draw left.

**Comment by dustintwatkins** [comment]
What happened here was the card you drew was replaced with a locomotive card. (We are considering adding functionality to notify the players the face-up pile has been updated to avoid confusion). Whenever the faceup deck has 3 locomotives, it is shuffled immediately with a seed unique to each game. It just so happens that other cards in the face-up pile were replaced with the same color card. The bank was not updated for the other players because you had one more draw left. We send commands once your turn is over, meaning two cards are drawn. Once your turn is over, all other clients are notified and their respective decks will be shuffled with the same seed and the face-up cards will have been updated.
