### ISSUE TITLE
turn error

### ISSUE THREAD

**Issue by ezrajc** [cs340tabyu/cs340summer2018#20]
I drew a card from the top of the deck. Then it wouldnt let me draw another train or draw destination cards, while displaying a message saying it was no longer my turn. Then it let me lay a route however.

**Comment by dustintwatkins** [comment]
The state pattern was not properly implemented. Initially, the claim route methods were not on the state pattern. This is why you could claim a route but not draw another card. We have now refactored and moved the claim route logic to the states, so that each state is responsible for determining the behavior of claim route.
By doing this, we also fixed the bug of being able to claim a route after drawing one card.
