### ISSUE TITLE
Game started with only one player

### ISSUE THREAD

**Issue by tylermercer** [cs340tabyu/cs340summer2018#51]
Created a game that required two players. As soon as the user joined the game and chose their player, it started the game. The user was then stuck in an infinite loop of Draw Destination Ticket screens.

**Comment by tylermercer** [comment]
In addition, the game that was started was apparently not removed from the game list.

**Comment by dsegrera** [comment]
This is a problem that only happens when the server is running on a different computer than the client when the client is connected to the BYU Ethernet. When I joined a game with someone else in it and picked my color, the game started with just me in it. It says that the other player is in the game on the info, but it’s wrong: they aren’t actually in the game when the game starts.

**Comment by dsegrera** [comment]
Once the other person joined the game, the game started automatically without me in it. I tried to join another game, but it doesn’t update and still shows that I’m in the other game. Now I’m stuck and I can’t do anything. Reproduced by all members of team.

**Comment by gaskint** [comment]
Wasn't able to reproduce. When a game is full all players in the game automatically join. If one of the users who had joined the game doesn't have their client open any more than the game will still start for everybody else, but will never actually start because the player who doesn't have a client will never select their tickets, but we consider that case outside the realm of our supported features, all players must have a client running in order for the game to work. Additionally, we weren't able to reproduce the bug where there is an infinite loop of select destination ticket screens.
